version: 0.2
phases:
  build:
    commands:
      -pip install -r requirements.txt -t .
  post_build:
    commands:
      - python --version
      - python lambda_function.py
artifacts:
  files:
    - '**/*'